service: hello
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x

functions:
  users:
    handler: src/index.handler
    events:
      - http:
          path: /api/starships
          method: GET
      - http:
          path: /api/people
          method: POST

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node18
    define:
      "process.env.NODE_ENV": '"production"'

plugins:
  - serverless-esbuild
  - serverless-offline
